// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAniwwXbd4YcfBbHyQwEUiYs1Ijb5JpOWc',
    appId: '1:1085476346200:web:6f753e8d1eb13a74f5ed2d',
    messagingSenderId: '1085476346200',
    projectId: 'note-9e1e8',
    authDomain: 'note-9e1e8.firebaseapp.com',
    storageBucket: 'note-9e1e8.firebasestorage.app',
    measurementId: 'G-TWMGTP5JMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6T7PwVEaK1-9VNvLDT3jo5l4mtDI0kXs',
    appId: '1:1085476346200:android:c77e3759f58789e6f5ed2d',
    messagingSenderId: '1085476346200',
    projectId: 'note-9e1e8',
    storageBucket: 'note-9e1e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiTJfueqn6zAvdfa_dxeK8QjCbAlBY9qs',
    appId: '1:1085476346200:ios:769970e6af3f6034f5ed2d',
    messagingSenderId: '1085476346200',
    projectId: 'note-9e1e8',
    storageBucket: 'note-9e1e8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiTJfueqn6zAvdfa_dxeK8QjCbAlBY9qs',
    appId: '1:1085476346200:ios:769970e6af3f6034f5ed2d',
    messagingSenderId: '1085476346200',
    projectId: 'note-9e1e8',
    storageBucket: 'note-9e1e8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAniwwXbd4YcfBbHyQwEUiYs1Ijb5JpOWc',
    appId: '1:1085476346200:web:0c06ce4195a2b274f5ed2d',
    messagingSenderId: '1085476346200',
    projectId: 'note-9e1e8',
    authDomain: 'note-9e1e8.firebaseapp.com',
    storageBucket: 'note-9e1e8.firebasestorage.app',
    measurementId: 'G-QHFGLJ87TH',
  );
}
